[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  # Optional: Set dummy values for build
  MONGODB_URI = "mongodb://localhost:27017/dummy"
  MONGODB_DATABASE = "dummy"
  NEXTAUTH_SECRET = "dummy-secret-for-build"
  NEXTAUTH_URL = "http://localhost:3000"

[context.production.environment]
  # These will override the build values
 MONGODB_URI=mongodb+srv://aweke2011:6MQLbWEw9Xhhu-j@gold.av49bjz.mongodb.net/gold?retryWrites=true&w=majority
NEXTAUTH_SECRET=9Wh3xJTU/PiHPIiXun2eYVjjOErHXPGvXB6oAvjSaJI=
NEXTAUTH_URL=http://localhost:3000
DATABASE_NAME =gold