import sanitizeHtml from "sanitize-html";

const ALLOWED_TAGS = [
  "p",
  "br",
  "hr",
  "div",
  "span",
  "strong",
  "b",
  "em",
  "i",
  "u",
  "s",
  "strike",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "dl",
  "dt",
  "dd",
  "a",
  "img",
  "figure",
  "figcaption",
  "blockquote",
  "pre",
  "code",
  "kbd",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "tr",
  "th",
  "td",
  "caption",
  "colgroup",
  "col",
  "mark",
  "small",
  "sub",
  "sup",
  "ins",
  "del",
  "abbr",
  "dfn",
  "q",
  "cite",
  "video",
  "audio",
  "source",
  "picture",
  "iframe",
];

const ALLOWED_ATTRIBUTES: Record<string, string[]> = {
  a: ["href", "target", "rel", "title", "class"],
  img: ["src", "alt", "title", "class", "width", "height", "loading"],
  video: ["src", "controls", "poster", "class", "width", "height"],
  audio: ["src", "controls"],
  iframe: [
    "src",
    "title",
    "allow",
    "allowfullscreen",
    "frameborder",
    "width",
    "height",
    "class",
  ],
  source: ["src", "type"],
  code: ["class"],
  span: ["class"],
  div: ["class"],
  th: ["colspan", "rowspan"],
  td: ["colspan", "rowspan"],
};

const ALLOWED_IFRAME_HOSTS = [
  "www.youtube.com",
  "youtube.com",
  "www.youtube-nocookie.com",
  "player.vimeo.com",
  "vimeo.com",
  "docs.google.com",
  "drive.google.com",
  "maps.google.com",
];

export function sanitizeBlogHtml(dirty: string): string {
  if (!dirty) return "";
  return sanitizeHtml(dirty, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRIBUTES,
    allowedIframeHostnames: ALLOWED_IFRAME_HOSTS,
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowProtocolRelative: false,
    disallowedTagsMode: "discard",
    transformTags: {
      a: sanitizeHtml.simpleTransform(
        "a",
        { rel: "noopener noreferrer", target: "_blank" },
        true
      ),
    },
  });
}
